const type = {
  ADD_ADDRESS: "ADD_ADDRESS",
  DELETE_ADDRESS: "DELETE_ADDRESS",
  EDIT_ADDRESS: "EDIT_ADDRESS",
  CHANGE_DEFAULT_ADDRESS: "CHANGE_DEFAULT_ADDRESS",
  ADD_CART_ITEM: "ADD_CART_ITEM",
  CHANGE_QUANTITY_CART: "DECREMENT_QUANTITY_CART",
};

export default type;
