const type = {
  ADD_ADDRESS: "ADD_ADDRESS",
  DELETE_ADDRESS: "DELETE_ADDRESS",
  EDIT_ADDRESS: "EDIT_ADDRESS",
  CHANGE_DEFAULT_ADDRESS: "CHANGE_DEFAULT_ADDRESS",
  ADD_CART_ITEM: "ADD_CART_ITEM",
  CHANGE_QUANTITY_CART: "DECREMENT_QUANTITY_CART",
  ADD_FILTER_PRODUCT: "ADD_Filter_PRODUCT",
  REMOVE_FILTER_PRODUCT: "REMOVE_FILTER_PRODUCT",
  ADD_BRAND_FILTER: "ADD_BRAND_FILTER",
  REMOVE_BRAND_FILTER: "REMOVE_BRAND_FILTER",
  ADD_PRICE_FILTER: "ADD_PRICE_FILTER",
  REMOVE_PRICE_FILTER: "REMOVE_PRICE_FILTER",
  ADD_RATING_FILTER: "ADD_RATING_FILTER",
  REMOVE_RATING_FILTER: "REMOVE_RATING_FILTER",
};

export default type;
